/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Introduction',
      items: [
        {
          type: 'autogenerated',
          dirName: 'introduction'
        },
      ]
    }
  ],
  contributorSidebar: [
    { 
      type: 'autogenerated',
      dirName: 'contributor-guide'
    },
    // {
    //   label: 'Contributor Guide',
    //   type: 'category',
    //   items: [
    //     { 
    //       type: 'autogenerated',
    //       dirName: 'contributor-guide'
    //     },
    //   ]
    // }
  ],
};

module.exports = sidebars;
